# Generated by Django 4.0.3 on 2022-03-25 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejobsweb', '0005_remove_post_created_on_remove_post_like_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
