# Generated by Django 4.0.3 on 2022-03-25 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejobsweb', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
