# Generated by Django 4.0.3 on 2022-03-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejobsweb', '0009_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default=None, upload_to='posts_by_users'),
        ),
    ]
