# Generated by Django 4.0.3 on 2022-03-25 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejobsweb', '0010_alter_post_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
