# Generated by Django 4.0.3 on 2022-03-28 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejobsweb', '0017_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
