# Generated by Django 4.0.3 on 2022-04-01 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejobsweb', '0021_alter_post_likes_likebutton'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeButton',
        ),
    ]
