# Generated by Django 4.0.3 on 2022-04-01 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejobsweb', '0023_room2_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='Room2',
            new_name='room',
        ),
    ]
