# Generated by Django 4.0.3 on 2022-04-01 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejobsweb', '0025_rename_room2_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='reciever',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Friendlist',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
