# Generated by Django 4.0.3 on 2022-04-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejobsweb', '0027_friendrequest_friendlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(default=None, upload_to='Profession_Images')),
                ('about', models.TextField()),
            ],
        ),
    ]
