# Generated by Django 4.0.3 on 2022-07-04 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejobsweb', '0030_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profession',
            new_name='Blog',
        ),
    ]
