# Generated by Django 4.0.3 on 2022-07-05 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejobsweb', '0031_rename_profession_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='about',
            new_name='content',
        ),
    ]
