# Generated by Django 4.0.3 on 2022-07-14 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejobsweb', '0032_rename_about_blog_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
