# Generated by Django 4.0.3 on 2022-08-02 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejobsweb', '0038_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
