# Generated by Django 4.0.3 on 2022-08-02 05:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ejobsweb', '0039_delete_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('img', models.ImageField(default=None, upload_to='Company Profile Picture')),
                ('location', models.CharField(max_length=50)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('url', models.URLField(default=None)),
                ('about', models.TextField()),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ejobsweb.profession')),
            ],
        ),
    ]
