# Generated by Django 4.0.3 on 2022-08-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejobsweb', '0044_experience_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='img',
            field=models.ImageField(default=None, null=True, upload_to='experience_img'),
        ),
    ]
