# Generated by Django 4.0.3 on 2022-08-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejobsweb', '0045_experience_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='designation',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
